# Site settings
title: Nivalis Designs
email: info@nivalisdesigns.com
tagline: Your small business resource to help you with your shopify implementation, ecommerce operations, and digital marketing.
description:
image: /img/header.jpg
baseurl: / # the subpath of your site, e.g. /blog/
url: https://nivalisdesigns.com # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
